# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 9689539980f9351409b39c19775b7496a5c190b63dd1e56060c4708c933e9ad770c685121e026b334de8205063b2626691fd9b8e2c3af849d83c6e539ec0fb82

test:
  domain_name: example.com 
  secret_key_base: 62e11673f88393732b908f84597cb3a7dd1aa51a222ea911c96192881831567c71023ce211b752d302ea7577262eb07b3e4010ca7e4fca21cfc67498684fcc79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
